### ISSUE TITLE
Determining thicknessArray

### ISSUE THREAD

**Issue by aflofo** [nasa/pyturbo-aero#1]
Hi I am used to providing camber, chord length, and thickness to chord ratio to something like a DCA airfoil. Curious if there is a general rule of thumb to estimate the thicknessArray from the thickness to chord ratio?

**Comment by pjuangph** [comment]
No I think you are thinking of a NACA airfoil. Those you plug in the thickness to chord into the equation. Thickness array is the chord normalized perpendicular distances from the camber line. 

Have you tried the tutorial on Google Colab? Try adding additional values into the thickness array and plotting. It might make things more clear.

**Comment by aflofo** [comment]
Yeah I looked at the Notebook I just wasn't sure when you are in the design process how you know exactly what the thicknessArray values should be?
![image](https://user-images.githubusercontent.com/112926272/203403423-3c992fe4-89b9-4924-b254-de73ac4cf7f3.png)
Is there some stress testing involved?

**Comment by pjuangph** [comment]
Only if you want it to be. Usually you pick something and run CFD, see if what your losses are, then adjust. You can pair the design process with FEA and run multi-objective optimization (see glennopt). There's no easy button. These are just pieces of the puzzle. You have to do some coding to pair it with CFD or FEA.
