### ISSUE TITLE
[Question] TypeError when using comb() function  when using 2d airfoil design tutorial

### ISSUE THREAD

**Issue by YanshanKaguya** [nasa/pyturbo-aero#11]
Dear Developer,
I have encountered an issue while utilizing  "Building Suction and Pressure side and the Leading edge"of pyturbo-aero package.An error called "TypeError: comb() takes 2 positional arguments but 3 were given" displayed.More details attached in pictures。
![code](https://github.com/user-attachments/assets/70822224-5a32-4777-9689-6eba38a7832d)
![run](https://github.com/user-attachments/assets/8321f4c4-f264-4832-8218-8ce9c568975b)
I am using Python 3.12, and the version of the pyturbo-aero  package I am working with is 1.0.0.Could you please advise on how to address this problem?Thank you for your assistance and support.
Best regards.

**Comment by pjuangph** [comment]
I have fixed some issues with pyturbo-aero. Please install the latest version and give the tutorials a try. 
`pip install -U pyturbo-aero`
