### ISSUE TITLE
'airfoil2D' cannot be imported  from 'pyturbo.aero.airfoil2D'

### ISSUE THREAD

**Issue by YanshanKaguya** [nasa/pyturbo-aero#12]
excuse me, dear developers.There's a new error  after implementing the solution when using 2D_Design Tutorial.It seems that "ImportError: cannot import name 'airfoil2D' from 'pyturbo.aero.airfoil2D' (E:\anaconda\python\studycode\pyturbo-aero-main\pyturbo\aero\airfoil2D.py). Did you mean: 'Airfoil2D'?"
![run2](https://github.com/user-attachments/assets/eeb76bb0-6a80-4182-8c5f-2606c4d6a774)
![code2](https://github.com/user-attachments/assets/c91f07fb-645d-4638-95eb-a2b3d1320bb8)

**Comment by pjuangph** [comment]
Yes, it should be Airfoil2D. You might want to update your code or something. I think you have the old version of all these files.
