### ISSUE TITLE
Sample code stack_type.centroid way to failure

### ISSUE THREAD

**Issue by siwuxei** [nasa/pyturbo-aero#4]
Thank you for your work, the program has helped me a lot. But here are some mistakes. When running the sample code, the stacking along the center fails.
![image](https://github.com/nasa/pyturbo-aero/assets/50586809/b77687a7-903c-4956-a02e-0a59699bb372)

**Comment by siwuxei** [comment]
![image](https://github.com/nasa/pyturbo-aero/assets/50586809/6b461518-c1db-4167-a2fc-bfcb6903cfc2)

**Comment by pjuangph** [comment]
Thank you for finding this. I'll do some investigation and let you know.

**Comment by pjuangph** [comment]
Give the tutorial a try again
